name: Build APK with Buildozer

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libstdc++6 zip unzip openjdk-17-jdk

      - name: Install Android SDK
        uses: android-actions/setup-android@v2

      - name: Install Android Build Tools
        run: sdkmanager "build-tools;34.0.0" "platform-tools" "platforms;android-34"

      - name: Add AIDL to PATH
        run: echo "$ANDROID_SDK_ROOT/build-tools/34.0.0" >> $GITHUB_PATH

      - name: Verify aidl installation
        run: aidl --version || echo "AIDL not found!"

      - name: Set aidl path for Buildozer
        run: echo "BUILD_AIDL=$ANDROID_SDK_ROOT/build-tools/34.0.0/aidl" >> $GITHUB_ENV

      - name: Install Buildozer
        run: pip install buildozer cython

      - name: Build APK
        run: buildozer -v android debug

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: android-apk
          path: bin/*.apk
