name: Build APK

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4   # تحديث checkout

      # Cache buildozer
      - name: Cache Buildozer
        uses: actions/cache@v4      # تحديث cache
        with:
          path: .buildozer
          key: ${{ runner.os }}-${{ hashFiles('buildozer.spec') }}

      # Install Android SDK
      - name: Install Android SDK
        uses: android-actions/setup-android@v2

      # Build APK using Buildozer action
      - name: Build with Buildozer
        uses: ArtemSBulgakov/buildozer-action@v1
        id: buildozer
        with:
          command: android debug
          buildozer_version: master

      # Upload APK artifact
      - name: Upload artifacts
        uses: actions/upload-artifact@v4   # تحديث upload-artifact
        with:
          name: package
          path: ${{ steps.buildozer.outputs.filename }}
